/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import static library_package.addStudent.invailedNumber;
import static library_package.addStudent.invailedString;

/**
 *
 * @author englu_2ecwi4v
 */
public class addLibrarian extends javax.swing.JFrame {

    /**
     * Creates new form addStudent
     */
    public addLibrarian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tssn = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tmName = new javax.swing.JTextField();
        tlName = new javax.swing.JTextField();
        tcountry = new javax.swing.JTextField();
        tcity = new javax.swing.JTextField();
        tstreet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgender = new javax.swing.JTextField();
        tmajor = new javax.swing.JTextField();
        sn = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        mn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        cit = new javax.swing.JLabel();
        str = new javax.swing.JLabel();
        bdd = new javax.swing.JLabel();
        gen = new javax.swing.JLabel();
        maj = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tlang = new javax.swing.JTextField();
        tsalary = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        lang = new javax.swing.JLabel();
        sal = new javax.swing.JLabel();
        birthDate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        setLocation(new java.awt.Point(530, 98));
        setMinimumSize(new java.awt.Dimension(805, 615));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("SSN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 20));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Futher's Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 20));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Country");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 60, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Street");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 30));

        tssn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tssnActionPerformed(evt);
            }
        });
        getContentPane().add(tssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 260, 30));

        tfName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 260, 30));

        tmName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 260, 30));

        tlName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 260, 30));

        tcountry.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 260, 30));

        tcity.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 260, 30));

        tstreet.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 260, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Birth Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Major");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, 30));

        tgender.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 260, 30));

        tmajor.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tmajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 260, 30));

        sn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        sn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 280, 30));

        fn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        fn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 260, 30));

        mn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        mn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 240, 30));

        ln.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ln.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 230, 30));

        con.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        con.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 260, 30));

        cit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cit.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(cit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 260, 30));

        str.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        str.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(str, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 270, 30));

        bdd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bdd.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(bdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 350, 30));

        gen.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        gen.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 220, 30));

        maj.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        maj.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(maj, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 230, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/add member.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 180, 120));

        jLabel24.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel24.setText("ADD A LIBRARIAN");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 360, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/ssaavvee.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 190, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/close.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 180, 40));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel23.setText("Language");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 70, 40));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel25.setText("Salary");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 70, 30));

        tlang.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 260, 30));

        tsalary.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 260, 30));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 220, 30));

        lang.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lang.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 260, 30));

        sal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        sal.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 260, 30));

        birthDate.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 260, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/small frame background.PNG"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tssnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String url,user,password, ssn,fname,mname,lname,country,city,street,bd,gender,major,eid,salary,language;
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        
        int c=0;
            ssn = tssn.getText();
            fname = tfName.getText();
            mname = tmName.getText();
            lname= tlName.getText();
            country = tcountry.getText();
            city = tcity.getText();
            street = tstreet.getText();
            bd= df.format(birthDate.getDate());
            
            
            String []words = bd.split("/");
       //     LocalDate d = LocalDate.of(Integer.parseInt(words[0]),Integer.parseInt(words[1]), Integer.parseInt(words[2]));
            int age =  LocalDate.now().getYear() - Integer.parseInt(words[2]);
            
            gender=tgender.getText();
            major=tmajor.getText();
            salary= tsalary.getText();
            language = tlang.getText();
           if(  invailedNumber(ssn)){
             sn.setText("Invalid Number");
             c++;
             }
           else if(99999>Integer.parseInt(ssn)||Integer.parseInt(ssn)>1000000) {
               sn.setText("Invalid Number");
             c++;
           }
             else{
               sn.setText("");  
             }
             if( invailedString(fname))
             {
               fn.setText("Invalid Name");  
               c++;
             }
             else{
               fn.setText("");  
             }
             if(invailedString(mname))
             {
                mn.setText("Invalid Name");
                c++;
             }
             else{
               mn.setText("");  
             }
              if(invailedString(lname))
             {
                ln.setText("Invalid Name");
                c++;
             }
             else{
               ln.setText("");  
             }
               if(invailedString(country))
             {
                con.setText("Invalid Name");
                c++;
             }
             else{
               con.setText("");  
             }
                if(invailedString(city))
             {
                cit.setText("Invalid Name");
                c++;
             }
             else{
               cit.setText("");  
             }
                 if(invailedString(street))
             {
                str.setText("Invalid Name");
                c++;
             }
             else{
               str.setText("");  
             }
             if(age <24)
             {
               
               bdd.setText("The Age of the Professor is Not acceptable!");  
               c++;
             }
             else{
               bdd.setText("");  
             }
              if(invailedString(gender))
             {
                gen.setText("Invalid Gender");
                c++;
             }
              else if(!(gender.equalsIgnoreCase("female")||gender.equalsIgnoreCase("male"))){
               gen.setText("Invalid Gender");
                c++;
    }
             else{
               gen.setText("");  
             }
               if(invailedString(major))
             {
                maj.setText("Invalid Name");
                c++;
             }
             else{
               maj.setText("");  
             }
                  
             if(invailedNumber(salary))
             {
               sal.setText("Invalid Number");  
               c++;
             }
            else if (1500>Integer.parseInt(salary) ){
               sal.setText("Invalid Salary");
               c++;
               
             }
             else{
               sal.setText("");  
             }
              if(invailedString(language))
             {
                lang.setText("Invalid Name");
                c++;
             }
             else{
               lang.setText("");  
             }
             if(c!=0){
                 new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"The Date You Have Entered is Not acceptable! Try Again Please.",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
             }
             else{
        try {
          //   DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            //String url,user,password, ssn,fname,mname,lname,country,city,street,bd,gender,major,eid,salary,lang;
            
            url= "jdbc:oracle:thin:@localhost:1521:xe";
            user="c##library";
            password="123456789";
           
            
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt=con.createStatement();   
           // String sqlstr="insert into employee values ("+ ssn +",'"+ fname+ "','"+mname+"','"+lname+"','"+country+"','"+city+"','"+street+"','"+bd+"','"+gender+"','"+major+"',"+"empid.nextval,"+salary+",'"+lang+"')";
            String sqlstr1="insert into person values ("+ ssn +",'"+ fname+ "','"+mname+"','"+lname+"','"+country+"','"+city+"','"+street+"',"+"TO_DATE('"+bd+"', 'DD/MM/YYYY'),'"+gender+"')";
            stmt.execute(sqlstr1);
            String sqlstr2="insert into employee values ("+ ssn +",empid.nextval,"+ salary+ ")";
            stmt.execute(sqlstr2);
            String sqlstr3="insert into librarian values (empid.currval,"+ssn +",'"+language+"')";
            stmt.execute(sqlstr3);
            con.setAutoCommit(false);
            con.commit();
            con.close();
            new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Done!",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
          
         
        } catch (SQLException ex) {
        new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"An error occurred! "+ex.getMessage(),NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addLibrarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bdd;
    private com.toedter.calendar.JDateChooser birthDate;
    private javax.swing.JLabel cit;
    private javax.swing.JLabel con;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lang;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel maj;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel sal;
    private javax.swing.JLabel sn;
    private javax.swing.JLabel str;
    private javax.swing.JTextField tcity;
    private javax.swing.JTextField tcountry;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tgender;
    private javax.swing.JTextField tlName;
    private javax.swing.JTextField tlang;
    private javax.swing.JTextField tmName;
    private javax.swing.JTextField tmajor;
    private javax.swing.JTextField tsalary;
    private javax.swing.JTextField tssn;
    private javax.swing.JTextField tstreet;
    // End of variables declaration//GEN-END:variables
}
