/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import static library_package.addStudent.invailedNumber;
import static library_package.addStudent.invailedString;

/**
 *
 * @author 2021
 */
public class addprogram extends javax.swing.JFrame {

    /**
     * Creates new form programf
     */
    public addprogram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pname = new javax.swing.JTextField();
        pssn = new javax.swing.JTextField();
        proid = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sd = new com.toedter.calendar.JDateChooser();
        ed = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(530, 98));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pname.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 270, 40));

        pssn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(pssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 270, 40));

        proid.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(proid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 270, 40));

        price.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 270, 40));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 40));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel26.setText("End Date");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 40));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel27.setText("Start Date");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 40));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setText("Professor ID");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 180, 40));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel29.setText("Professor SSN");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 40));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel30.setText("Program Name");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/ssaavvee.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 230, 40));

        l1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 210, 40));

        l2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 210, 40));

        l3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 210, 40));

        l4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 270, 40));

        l5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 270, 40));

        l6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        l6.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 200, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/addprogram_adobespark.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 130, 150));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("ADD A PROGRAM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        sd.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(sd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 270, 40));

        ed.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 270, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/close.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 220, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/small frame background.PNG"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     String url,user,password,pnamee,pssnn,proidd,sdd,edd,pr;
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        int c=0;
            
           pnamee = pname.getText();
            pssnn = pssn.getText();
            proidd= proid.getText();
            sdd= df.format(sd.getDate());
            edd= df.format(ed.getDate());
            pr=price.getText();
            
            String []start = sdd.split("/");
            String []end = edd.split("/"); 
            
            
            int year =  Integer.parseInt(end[2]) - Integer.parseInt(start[2]);
            int month =  Integer.parseInt(end[1]) - Integer.parseInt(start[1]);
            int day =  Integer.parseInt(end[0]) - Integer.parseInt(start[0]);
            
            System.out.println(day);
            System.out.println(month);
            System.out.println(year);
        
             if( invailedString(pnamee))
             {
               l1.setText("Invalid Name");  
               c++;
             }
             else{
               l1.setText("");  
             }
             if(invailedNumber(pssnn))
             {
                l2.setText("Invalid Number");
                c++;
             }
             else if(99999>Integer.parseInt(pssnn)||Integer.parseInt(pssnn)>1000000) {
               l2.setText("Invalid SSN Number");
               c++;
           }
             else{
              l2.setText("");  
             }
              if(invailedNumber(proidd))
             {
                l3.setText("Invalid Number");
                c++;
             }
             else{
               l3.setText("");  
             }
            if(invailedNumber(pr))
             {
                l6.setText("Invalid Number");
                c++;
             }
             else{
               l6.setText("");  
             }
            if(year <0 )
              new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"The End Date You Have Entered is Befor The Start Date",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            else if(month <0){
                      new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"The End Date You Have Entered is Befor The Start Date",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
                      }
            else if(day <0)new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"The End Date You Have Entered is Befor The Start Date",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            
            
            if(c!=0){
                 new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"The Data You Have Entered is Not acceptable! Try Again Please.",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
             }
            else{
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
     // DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
      DateFormat df2 = new SimpleDateFormat("dd/MM/yyyy");
      //SimpleDateFormat spd= new SimpleDateFormat(df);
      //      String url,user,password,pnamee,pssnn,proidd,sdd,edd,pr;
            
            url= "jdbc:oracle:thin:@localhost:1521:xe";
            user="c##library";
            password="123456789";
           
            
            pnamee = pname.getText();
            pssnn = pssn.getText();
            proidd= proid.getText();
            sdd= df.format(sd.getDate());
            edd= df2.format(ed.getDate());
            pr=price.getText();
           
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt=con.createStatement();   
         // String sqlstr1="insert into person values ("+ ssn +",'"+ fname+ "','"+mname+"','"+lname+"','"+country+"','"+city+"','"+street+"',"+"TO_DATE('"+bd+"', 'DD/MM/YYYY'),'"+gender+"')";
            // String sqlstr="insert into employee values ("+ ssn +",'"+ fname+ "','"+mname+"','"+lname+"','"+country+"','"+city+"','"+street+"','"+bd+"','"+gender+"','"+major+"',"+"empid.nextval,"+salary+",'"+lang+"')";
            String sqlstr="insert into lprogram values (progId.nextval,'"+ pnamee+ "',"+pr+","+"TO_DATE('"+sdd+"', 'DD/MM/YYYY'),TO_DATE('"+edd+"', 'DD/MM/YYYY'),"+pssnn+","+proidd+")";
            stmt.execute(sqlstr);
            con.setAutoCommit(false);
            con.commit();
            con.close();
            new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Done!",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
              } catch (SQLException ex) {
              new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"An error occured!"+ex.getMessage(),NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
             java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addprogram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ed;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField price;
    private javax.swing.JTextField proid;
    private javax.swing.JTextField pssn;
    private com.toedter.calendar.JDateChooser sd;
    // End of variables declaration//GEN-END:variables
}
