/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;

/**
 *
 * @author englu_2ecwi4v
 */
public class addStudent extends javax.swing.JFrame {

    /**
     * Creates new form addStudent
     */
    public addStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tssn = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tmName = new javax.swing.JTextField();
        tlName = new javax.swing.JTextField();
        tcountry = new javax.swing.JTextField();
        tcity = new javax.swing.JTextField();
        tstreet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgender = new javax.swing.JTextField();
        tmajor = new javax.swing.JTextField();
        sn = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        mn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        cit = new javax.swing.JLabel();
        bdd = new javax.swing.JLabel();
        gen = new javax.swing.JLabel();
        maj = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        birthDate = new com.toedter.calendar.JDateChooser();
        str = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        setLocation(new java.awt.Point(530, 98));
        setMinimumSize(new java.awt.Dimension(805, 615));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("SSN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, 20));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 20));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Futher's Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 20));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Country");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 60, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Street");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 70, 30));

        tssn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 260, 30));

        tfName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 260, 30));

        tmName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 260, 30));

        tlName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 260, 30));

        tcountry.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 260, 30));

        tcity.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 260, 30));

        tstreet.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 260, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Birth Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 70, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Major");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 70, 40));

        tgender.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 260, 30));

        tmajor.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tmajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 260, 30));

        sn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        sn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 140, 30));

        fn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        fn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 100, 30));

        mn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        mn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 130, 30));

        ln.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ln.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 100, 30));

        con.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        con.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 140, 30));

        cit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cit.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(cit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 140, 30));

        bdd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bdd.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(bdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 310, 30));

        gen.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        gen.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 160, 30));

        maj.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        maj.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(maj, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 150, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/add member.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 180, 120));

        jLabel24.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel24.setText("ADD A STUDENT");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 300, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/ssaavvee.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/close.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 200, 40));

        birthDate.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 260, 30));

        str.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        str.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(str, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 140, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/small frame background.PNG"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean invailedString(String s){
         char []stringChar = s.toCharArray();
         for(int i =0;i<stringChar.length;i++){
       if(Character.isDigit(stringChar [i]) || !Character.isLetter(stringChar [i]) ){
             return true;
     }
         }
         return false;
     }
    public static boolean invailedNumber(String s){
         char []stringChar = s.toCharArray();
         for(int i =0;i<stringChar.length;i++){
       if(!Character.isDigit(stringChar [i]) ){
             return true;
     }
         }
         return false;
     }
    
   
    
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
           String url,user,password, ssn,fname,mname,lname,country,city,street,bd,gender,major,eid,salary,degree;
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        int c=0;
       ssn = tssn.getText();
            fname = tfName.getText();
            mname = tmName.getText();
            lname= tlName.getText();
            country = tcountry.getText();
            city = tcity.getText();
            street = tstreet.getText();
            bd= df.format(birthDate.getDate());
            
            String []words = bd.split("/");
            int age =  LocalDate.now().getYear() - Integer.parseInt(words[2]);
            
            gender=tgender.getText();
            major=tmajor.getText();
           if(  invailedNumber(ssn)){
             sn.setText("Invalid Number");
             c++;
             }
           else if(99999>Integer.parseInt(ssn)||Integer.parseInt(ssn)>1000000) {
               sn.setText("Invalid Number");
             c++;
           }
             else{
               sn.setText("");  
             }
             if( invailedString(fname))
             {
               fn.setText("Invalid Name");  
               c++;
             }
             else{
               fn.setText("");  
             }
             if(invailedString(mname))
             {
                mn.setText("Invalid Name");
                c++;
             }
             else{
               mn.setText("");  
             }
              if(invailedString(lname))
             {
                ln.setText("Invalid Name");
                c++;
             }
             else{
               ln.setText("");  
             }
               if(invailedString(country))
             {
                con.setText("Invalid Name");
                c++;
             }
             else{
               con.setText("");  
             }
                if(invailedString(city))
             {
                cit.setText("Invalid Name");
                c++;
             }
             else{
               cit.setText("");  
             }
                 if(invailedString(street))
             {
                str.setText("Invalid Name");
                c++;
             }
             else{
               str.setText("");  
             }
             if(age <17)
             {
               bdd.setText("The Age of the Student is Not acceptable!");  
               c++;
             }
            
             else{
               bdd.setText("");  
             }
              if(invailedString(gender))
             {
                gen.setText("Invalid Gender");
                c++;
             }
              else if(!(gender.equalsIgnoreCase("female")||gender.equalsIgnoreCase("male"))){
           gen.setText("Invalid Gender");
                c++;
    }
             else{
               gen.setText("");  
             }
               if(invailedString(major))
             {
                maj.setText("Invalid Name");
                c++;
             }
             else{
               maj.setText("");  
             }
             if(c!=0){
                 new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"The Date You Have Entered is Not acceptable! Try Again Please.",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
             }
             else{
        
        
        try {
            // TODO add your handling code here:
            url= "jdbc:oracle:thin:@localhost:1521:xe";
            user="c##library";
            password="123456789";
           
         
            
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt=con.createStatement();   
            
           // String sqlstr="insert into employee values ("+ ssn +",'"+ fname+ "','"+mname+"','"+lname+"','"+country+"','"+city+"','"+street+"','"+bd+"','"+gender+"','"+major+"',"+"empid.nextval,"+salary+",'"+lang+"')";
            String sqlstr1="insert into person values ("+ ssn +",'"+ fname+ "','"+mname+"','"+lname+"','"+country+"','"+city+"','"+street+"',"+"TO_DATE('"+bd+"', 'DD/MM/YYYY'),'"+gender+"')";
            stmt.execute(sqlstr1);
            String sqlstr3="insert into student values ("+ssn +",'"+major+"')";
            stmt.execute(sqlstr3);
            con.setAutoCommit(false);
            con.commit();
            con.close();
            new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Done!",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            //JOptionPane.showMessageDialog(null, "Done");
         
        } catch (SQLException ex) {
          new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"An error occurred! "+ex.getMessage(),NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
       //   JOptionPane.showMessageDialog(null, ex.getMessage());
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
            
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bdd;
    private com.toedter.calendar.JDateChooser birthDate;
    private javax.swing.JLabel cit;
    private javax.swing.JLabel con;
    private javax.swing.JLabel fn;
    private javax.swing.JLabel gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel maj;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel sn;
    private javax.swing.JLabel str;
    private javax.swing.JTextField tcity;
    private javax.swing.JTextField tcountry;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tgender;
    private javax.swing.JTextField tlName;
    private javax.swing.JTextField tmName;
    private javax.swing.JTextField tmajor;
    private javax.swing.JTextField tssn;
    private javax.swing.JTextField tstreet;
    // End of variables declaration//GEN-END:variables
}
