/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import javax.swing.JFrame;

/**
 *
 * @author englu_2ecwi4v
 */
public class book extends javax.swing.JFrame {
addbook add =new addbook();
BorrowBook borrow =new BorrowBook();
returnBook1 return1 = new returnBook1();
    /**
     * Creates new form book
     */
    public book() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        borrowBook = new javax.swing.JButton();
        returnBook = new javax.swing.JButton();
        addBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/back (1).jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 50, 50));

        borrowBook.setBackground(new java.awt.Color(255, 255, 255));
        borrowBook.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        borrowBook.setText("Borrow Book");
        borrowBook.setBorder(null);
        borrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookActionPerformed(evt);
            }
        });
        getContentPane().add(borrowBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 230, 40));

        returnBook.setBackground(new java.awt.Color(255, 255, 255));
        returnBook.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        returnBook.setText("Return Book");
        returnBook.setBorder(null);
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        getContentPane().add(returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 230, 40));

        addBook.setBackground(new java.awt.Color(255, 255, 255));
        addBook.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        addBook.setText("Add Book");
        addBook.setBorder(null);
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        getContentPane().add(addBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/return - Copy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1380, 805);
    }// </editor-fold>//GEN-END:initComponents

    private void borrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBookActionPerformed
       borrow.setVisible(true);
       add.setVisible(false);
       return1.setVisible(false);
    }//GEN-LAST:event_borrowBookActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
       borrow.setVisible(false);
       add.setVisible(true);
       return1.setVisible(false);
    }//GEN-LAST:event_addBookActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        borrow.setVisible(false);
       add.setVisible(false);
       return1.setVisible(true);
    }//GEN-LAST:event_returnBookActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Login.ho.setVisible(true);
       this.setVisible(false);
       borrow.setVisible(false);
       add.setVisible(false);
       return1.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton borrowBook;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton returnBook;
    // End of variables declaration//GEN-END:variables
}
