/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2021
 */
public class sindepartment extends javax.swing.JFrame {

    /**
     * Creates new form sindepartment
     */
    public sindepartment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tvalue = new javax.swing.JTextField();
        searchBy = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(530, 98));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 170, 30));

        searchBy.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by Book  ID", "Search by Book Name" }));
        searchBy.setBorder(null);
        searchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByActionPerformed(evt);
            }
        });
        getContentPane().add(searchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/SCIENCE_adobespark.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setText("SCIENCE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, 30));

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Number", "Book Name", "Auther F Name ", "Auther L Name", "Publishing house"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 320));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/search.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 170, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/show all books.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 230, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/close.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 230, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/small frame background.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url,user,password;
            
            url= "jdbc:oracle:thin:@localhost:1521:xe";
            user="c##library";
            password="123456789";
      
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt=con.createStatement();   
            
          String sqlstr="select Book_number, Book_Name,Auther_FName,Auther_LName,Publishing_house From Book where DNumber = 50"; 
          ResultSet rs = stmt.executeQuery(sqlstr);
          while(rs.next()){
          String bid = String.valueOf(rs.getInt("Book_number"));
          String bname = rs.getString("Book_Name");
          String afname = rs.getString("Auther_FName");
          String alname = rs.getString("Auther_lName");
          String pubhouse = rs.getString("Publishing_house");
          
          String tbData[] ={bid,bname,afname,alname,pubhouse};
          DefaultTableModel tblModel= (DefaultTableModel)jTable1.getModel();
          
          tblModel.addRow(tbData);
          
          }
            con.close();
            new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Done!",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            
         
        } catch (java.sql.SQLException ex) {
          new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"An error occurred! "+ex.getMessage(),NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
       //   JOptionPane.showMessageDialog(null, ex.getMessage());
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          int c= searchBy.getSelectedIndex();
     DefaultTableModel tblModel= (DefaultTableModel)jTable1.getModel();
     for(int i=0;i< tblModel.getRowCount();i++){
     tblModel.removeRow(i);
     }
        try {
            
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url,user,password;
            
            url= "jdbc:oracle:thin:@localhost:1521:xe";
            user="c##library";
            password="123456789";
      
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt=con.createStatement();  
            String sqlstr="";
            String value =tvalue.getText();
            switch (c){
                case 0:
                  sqlstr ="select Book_number, Book_Name,Auther_FName,Auther_LName,Publishing_house From Book where DNumber = 50 and Book_number ="+value;    
                  break;  
                case 1:    
                  sqlstr ="select Book_number, Book_Name,Auther_FName,Auther_LName,Publishing_house From Book where DNumber = 50 and Book_name ='"+value+"'";
                  break;
            }
           //sqlstr ="select Book_number, Book_Name,Auther_FName,Auther_LName,Publishing_house From Book where DNumber = 10"; 
           ResultSet rs = stmt.executeQuery(sqlstr);
          while(rs.next()){
          String bid = String.valueOf(rs.getInt("Book_number"));
          String bname = rs.getString("Book_Name");
          String afname = rs.getString("Auther_FName");
          String alname = rs.getString("Auther_lName");
          String pubhouse = rs.getString("Publishing_house");
          
          String tbData[] ={bid,bname,afname,alname,pubhouse};
         
         
          tblModel.addRow(tbData);
          
          }
            con.close();
            new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Done!",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            
         
        } catch (java.sql.SQLException ex) {
          new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"An error occurred! "+ex.getMessage(),NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
       //   JOptionPane.showMessageDialog(null, ex.getMessage());
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sindepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sindepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sindepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sindepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sindepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> searchBy;
    private javax.swing.JTextField tvalue;
    // End of variables declaration//GEN-END:variables
}
