/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;

/**
 *
 * @author englu_2ecwi4v
 */
public class updateStudent extends javax.swing.JFrame {

    /**
     * Creates new form updateStudent
     */
    public updateStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateBy = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tssn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tdata = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(530, 98));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateBy.setBackground(new java.awt.Color(255, 255, 204));
        updateBy.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        updateBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Name", "Middle Name", "Last Name", "Country", "City", "Street", "Birth Date", "Major" }));
        updateBy.setBorder(null);
        updateBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateByActionPerformed(evt);
            }
        });
        getContentPane().add(updateBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 290, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Student SSN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 166, 33));

        tssn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 290, 39));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Update Column :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 166, 33));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("New Data");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 166, 33));

        tdata.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(tdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 290, 39));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 166, 33));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 166, 33));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 166, 33));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/update.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 230, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/update icon_adobespark.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel10.setText("UPDATE STUDENT");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 340, 90));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/close.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 190, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_package/small frame background.PNG"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateByActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ssn= tssn.getText();
        String data = tdata.getText();
         try {
             //DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url,user,password;
            
            url= "jdbc:oracle:thin:@localhost:1521:xe";
            user="c##library";
            password="123456789";
            
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt=con.createStatement();   
         
            String sqlstr1="";
            int c =updateBy.getSelectedIndex();
            DateFormat df1 = new SimpleDateFormat("dd/MM/yyyy");
            //data.
            boolean symbol= false;
          
            char []datachar= data.toCharArray();
               for(int i=0;i<datachar.length;i++) {
			//Character.isDigit(0)
			if(!Character.isLetter(datachar[i]) && datachar[i]!=' ') {
				symbol=true;
				break;
                        }
                      
               }
             if(c!= 6 && symbol==true){
                  new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Invalid Data! ",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
             }
            
             else {
            switch (c){
                case 0:
                  sqlstr1 = "update person set First_Name ='"+data+"'where ssn ="+ssn;  
                  break;
                case 1:
                  sqlstr1 = "update person set Middle_Name ='"+data+"'where ssn ="+ssn;  
                  break; 
                case 2:
                  sqlstr1 = "update person set Last_Name ='"+data+"'where ssn ="+ssn;  
                  break;
                case 3:
                  sqlstr1 = "update person set country ='"+data+"'where ssn ="+ssn;  
                  break; 
                case 4:
                  sqlstr1 = "update person set city ='"+data+"'where ssn ="+ssn;  
                  break;  
                case 5:  
                  sqlstr1 = "update person set street ='"+data+"'where ssn ="+ssn;  
                  break;  
                case 6:    
                  sqlstr1 = "update person set birth_date = TO_DATE('"+data+"', 'DD/MM/YYYY')where ssn ="+ssn;  
                  break;   
                case 7:
                  sqlstr1 = "update student set major = '"+data+"'where ssn ="+ssn;  
                  break;   
                   
            }
            System.out.println(c+"hello");   
            stmt.execute(sqlstr1);
            con.setAutoCommit(false);
            con.commit();
            con.close();
            new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"Done!",NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
               }
               }
         catch (SQLException ex) {
        new NoticeWindow( NoticeType.DEFAULT_NOTIFICATION,"An error occurred! "+ex.getMessage(),NoticeWindow.LONG_DELAY, NPosition.BOTTOM_RIGHT);
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tdata;
    private javax.swing.JTextField tssn;
    private javax.swing.JComboBox<String> updateBy;
    // End of variables declaration//GEN-END:variables
}
